name: graze
version: 0.1.0.0
github: "zuqq/graze"
author: "zuqq"

extra-source-files:
- README.md

dependencies:
- aeson
- async
- attoparsec
- base >= 4.7 && < 5
- base16-bytestring
- bytestring
- case-insensitive
- containers
- cryptohash-sha1
- directory
- filepath
- html-parse
- http-client
- http-client-tls
- http-media
- http-types
- network-uri
- optparse-applicative
- stm
- stm-chans
- text

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

executables:
  graze-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graze

tests:
  graze-doctest:
    main: Main.hs
    source-dirs: doctest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - doctest
    - graze

  graze-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers
    - graze
    - hspec
    - network
    - streaming-commons
    - wai-app-static
    - warp
