name:                graze
version:             0.1.0.0
github:              "zuqq/graze"
author:              "zuqq <noahheld17@gmail.com>"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/zuqq/graze#readme>

dependencies:
- SHA
- attoparsec
- base >= 4.7 && < 5
- bytestring
- containers
- directory
- filepath
- hashable
- http-client
- http-client-tls
- optparse-applicative
- stm
- tagsoup
- text
- transformers
- unordered-containers

library:
  source-dirs: src

executables:
  graze-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graze

tests:
  graze-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - doctest
    - graze
