name:                graze
version:             0.1.0.0
github:              "zuqq/graze"
author:              "zuqq <noahheld17@gmail.com>"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/zuqq/graze#readme>

dependencies:
- attoparsec
- base >= 4.7 && < 5
- base16-bytestring
- bytestring
- cryptohash-sha1
- directory
- filepath
- hashable
- http-client
- http-client-tls
- optparse-applicative
- stm
- tagsoup
- time
- transformers
- unordered-containers

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

executables:
  graze-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graze

tests:
  doc:
    main:                Main.hs
    source-dirs:         test/doc
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - doctest
    - graze

  unit:
    main:                Main.hs
    source-dirs:         test/unit
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graze
    - tasty
    - tasty-hunit
