name:    graze
version: 0.1.0.0
github:  "zuqq/graze"
author:  "zuqq <noahheld17@gmail.com>"

extra-source-files:
- README.md

dependencies:
- attoparsec
- base >= 4.7 && < 5
- base16-bytestring
- bytestring
- case-insensitive
- cryptohash-sha1
- directory
- filepath
- hashable
- http-client
- http-client-tls
- optparse-applicative
- stm
- tagsoup
- text
- transformers
- unordered-containers

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

executables:
  graze-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graze

tests:
  doctest:
    main:                Main.hs
    source-dirs:         doctest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - doctest
    - graze

  graze-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graze
    - tasty
    - tasty-hunit
